services:
  mariadb:
    image: mysql:8.4.0
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h localhost -u root -ppassword
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inception
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/database:/var/lib/mysql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    command:
      [
        "start",
        "--http-port",
        "7080",
        "--https-port",
        "7443",

      ]
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KC_DB: mysql
      KC_DB_URL_DATABASE: kc_db
      KC_DB_USERNAME: kc_admin
      KC_DB_PASSWORD: kc_password
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
      KC_HTTP_ENABLED: true
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key

    volumes:
      - ./docker/keycloak/themes:/opt/keycloak/themes/
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./server.crt:/opt/keycloak/conf/server.crt
      - ./server.key:/opt/keycloak/conf/server.key
    ports:
      - 7080:7080
      - 7443:7443
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      dozzle:
        condition: service_started

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - inception
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  inception:
    driver: bridge
