services:
  mariadb:
    container_name: mariadb
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h localhost -u root -ppassword
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - inception
    volumes:
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d/

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command:
      [
        "start-dev",
        "--http-port",
        "7080",
        "--https-port",
        "7443"
      ]
    restart: always
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KC_DB: mysql
      KC_DB_URL_DATABASE: kc_db
      KC_DB_USERNAME: kc_admin
      KC_DB_PASSWORD: kc_password
      KC_DB_URL_HOST: mariadb
      KC_DB_URL_PORT: 3306
    volumes:
      - ./docker/keycloak/themes:/opt/keycloak/themes/
    ports:
      - 7080:7080
      - 7443:7443
    networks:
      - inception
    depends_on:
      mariadb: 
        condition: service_healthy

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - inception

networks:
  inception:
    driver: bridge
